config/routes.rb
TStories::Application.routes.draw do
  devise_for :users
  root 'posts#index'

    resources :posts, only: [:new, :create, :show, :index] do
      resources :comments, only: [:new, :create]
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
validates :username, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully added.'
    else
      flash[:alert] = 'Comment unsuccessful'
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to '/posts', notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add a Comment</h1>

<%= simple_form_for [@post, @comment] do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, 'Submit Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "T Stories" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <% if request.env['PATH_INFO'] != new_user_registration_path && request.env['PATH_INFO'] != '/users' %>


        <nav class= 'top-bar'>
        <ul class= 'title-area'>
        <li class="name">
             <h1><%= link_to "T Stories", posts_path %> </h1>
        </li>
        </ul>
         <section class="top-bar-section">
          <ul class="right">
              <% if !user_signed_in? %>
                <li class='active'><%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="divider"></li>
                <li class='active'><%= link_to "Sign In", new_user_session_path %></li>
              <% else %>
                <li>Welcome <%= current_user.username %></li>
                <li class ='active'><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% end %>
          </ul>
          </section>
        </nav>



    <% end %>
<% if flash[:notice].present? %>
      <%= flash[:notice] %>
    <% end %>

    <% if flash[:alert].present? %>
      <%= flash[:alert] %>
    <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/index.html.erb
<h1> T Stories </h1>

  <% @posts.each do |post| %>
    <div>
      <%= link_to post.title, post %>
      <p><%= truncate(post.content, length: 100, omission: '...(continued)') %></p>
    </div>
  <% end %>
<%= link_to 'Add new T Story', new_post_path %>

app/views/posts/new.html.erb
<h1> Submit a T Story </h1>

<%= simple_form_for(@post) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, 'Submit T Story' %>
<% end %>

app/views/posts/show.html.erb
<h3> <%= @post.title %> </h3>
<p> <%= @post.content %></p>



<% if @post.comments.present? %>
  <div>
    <ul>
      <%  @post.comments.each do |comment| %>
        <li>
          <%= comment.body %>
        </li>
      <%end%>
    </ul>
  </div>
<% end %></br>

<%= link_to 'Add a Comment', new_post_comment_path(@post) %></br>
<%= link_to "Back to T Stories", posts_path %>